#spring:
#  datasource:
#    username: Josse
#    password:
#    url: jdbc:mysql://localhost:3306/suivi_dsn
#    driver-class-name: com.mysql.cj.jdbc.Driver
#
#  jpa:
#     show-sql: true
#     hibernate:
#       ddl-autao: update
#     properties.hibernate.dialect: org.hibernate.dialect.MySQL5Dialect